Repository paydelimon22/TC2008B, pull requests merged in 2024-11, with the labels that each got.

#6 1 integrate template project
  .gitignore
  README.md
  Server/__init__.py
  Server/agentsServer/agents_server.py
  Server/agentsServer/parkAgents/.gitignore
  Server/agentsServer/parkAgents/__init__.py
  Server/agentsServer/parkAgents/agent.py
  Server/agentsServer/parkAgents/city_files/2021_base.txt
  Server/agentsServer/parkAgents/city_files/2022_base.txt
  Server/agentsServer/parkAgents/city_files/2023_base.txt
  Server/agentsServer/parkAgents/city_files/mapDictionary.json
  Server/agentsServer/parkAgents/model.py
  Server/trafficServer/city_files/2021_base.txt
  Server/trafficServer/city_files/2022_base.txt
  Server/trafficServer/city_files/mapDictionary.json
  Server/trafficServer/server.py
  Server/trafficServer/server_traffic.py
  Server/trafficServer/trafficBase/__init__.py
  Server/trafficServer/trafficBase/agent.py
  Server/trafficServer/trafficBase/model.py
  Server/trafficServer/trafficBase/server.py
  visualization/index.html
  visualization/package-lock.json
  visualization/package.json
  visualization/park_agents.js
  visualization/styles.css
Labels: documentation, enhancement, good first issue, mesa

#10 feat: added objs and mtls for all objects to be rendered
  visualization/asstes/Bike/bike.mtl
  visualization/asstes/Bike/bike.obj
  visualization/asstes/Bike/wheel.mtl
  visualization/asstes/Bike/wheel.obj
  visualization/asstes/Obstacles/basketball_court.mtl
  visualization/asstes/Obstacles/basketball_court.obj
  visualization/asstes/Obstacles/football_field.mtl
  visualization/asstes/Obstacles/football_field.obj
  visualization/asstes/Obstacles/fountain.mtl
  visualization/asstes/Obstacles/fountain.obj
  visualization/asstes/Obstacles/rock1.mtl
  visualization/asstes/Obstacles/rock1.obj
  visualization/asstes/Obstacles/rock2.mtl
  visualization/asstes/Obstacles/rock2.obj
  visualization/asstes/Obstacles/trash_can.mtl
  visualization/asstes/Obstacles/trash_can.obj
  visualization/asstes/Obstacles/tree1.mtl
  visualization/asstes/Obstacles/tree1.obj
  visualization/asstes/Obstacles/tree2.mtl
  visualization/asstes/Obstacles/tree2.obj
  visualization/asstes/assets.png
  visualization/asstes/destination.mtl
  visualization/asstes/destination.obj
  visualization/asstes/grass.mtl
  visualization/asstes/grass.obj
  visualization/asstes/road.mtl
  visualization/asstes/road.obj
  visualization/asstes/traffic_light.mtl
  visualization/asstes/traffic_light.obj
Labels: Blender

#11 7 implement mesa model class
  Server/agentsServer/parkAgents/park_files/2021_base.txt
  Server/agentsServer/parkAgents/park_files/2022_base.txt
  Server/agentsServer/parkAgents/park_files/2023_base.txt
  Server/agentsServer/parkAgents/park_files/mapDictionary.json
Labels: bug, mesa

#12 7 implement mesa model class
  Server/agentsServer/parkAgents/model.py
Labels: bug, mesa

#14 9 server and visualization integration
  Server/agentsServer/agents_server.py
  Server/agentsServer/parkAgents/agent.py
  Server/agentsServer/parkAgents/model.py
  Server/agentsServer/park_files/2021_base.txt
  Server/agentsServer/park_files/2022_base.txt
  Server/agentsServer/park_files/2023_base.txt
  Server/agentsServer/park_files/mapDictionary.json
  visualization/park_agents.js
Labels: enhancement, mesa, WebGL

#17 feat: Camera rotation instead of translation
  visualization/park_agents.js
Labels: enhancement, WebGL

#18 15 use obj assets for visualization
  visualization/assets/Bike/Bike_Frame/bike_frame.mtl
  visualization/assets/Bike/Bike_Frame/bike_frame.obj
  visualization/assets/Bike/Bike_Wheel/bike_wheel.mtl
  visualization/assets/Bike/Bike_Wheel/bike_wheel.obj
  visualization/assets/Decorators/Scalable/Basketball_Court/basketball_court.mtl
  visualization/assets/Decorators/Scalable/Basketball_Court/basketball_court.obj
  visualization/assets/Decorators/Scalable/Football_Field/football_field.mtl
  visualization/assets/Decorators/Scalable/Football_Field/football_field.obj
  visualization/assets/Decorators/Scalable/Fountain/fountain.mtl
  visualization/assets/Decorators/Scalable/Fountain/fountain.obj
  visualization/assets/Decorators/Tile/Rock/rock.mtl
  visualization/assets/Decorators/Tile/Rock/rock1.obj
  visualization/assets/Decorators/Tile/Rock/rock2.obj
  visualization/assets/Decorators/Tile/Trash_Can/trash_can.mtl
  visualization/assets/Decorators/Tile/Trash_Can/trash_can.obj
  visualization/assets/Decorators/Tile/Tree/tree.mtl
  visualization/assets/Decorators/Tile/Tree/tree1.obj
  visualization/assets/Decorators/Tile/Tree/tree2.obj
  visualization/assets/Destination/destination.mtl
  visualization/assets/Destination/destination.obj
  visualization/assets/Tiles/Grass/grass.mtl
  visualization/assets/Tiles/Grass/grass.obj
  visualization/assets/Tiles/Road/road.mtl
  visualization/assets/Tiles/Road/road.obj
  visualization/assets/Traffic_Light/traffic_light.mtl
  visualization/assets/Traffic_Light/traffic_light.obj
  visualization/assets/load_obj.js
  visualization/instantiate_obj.js
  visualization/park_agents.js
Labels: enhancement, WebGL

#20 19 visualize all agent types
  Server/agentsServer/agents_server.py
  visualization/park_agents.js
Labels: enhancement, WebGL

#25 create all bikes with each step
  Server/agentsServer/parkAgents/agent.py
  visualization/park_agents.js
Labels: bug, mesa, WebGL

#29 22 bug bike and traffic light alignment
  Server/agentsServer/agents_server.py
  Server/agentsServer/parkAgents/agent.py
  Server/agentsServer/parkAgents/model.py
  visualization/park_agents.js
Labels: bug, enhancement, mesa, WebGL

#32 fix: default behaviour for traffic light roads
  Server/agentsServer/parkAgents/model.py
Labels: bug, mesa

#35 31 use variety of assets for tile decorations
  visualization/park_agents.js
Labels: enhancement, WebGL

#36 4 animate bike behaviour
  Server/agentsServer/agents_server.py
  visualization/park_agents.js
Labels: enhancement, WebGL

#53 Add Report
  Reporte_Movilidad_Urbana.pdf
Labels: documentation
